### ISSUE TITLE
Rebanding vhost user net plugin as Userspace CNI

### ISSUE THREAD

**Issue by rkamudhan** [intel/userspace-cni-network-plugin#12]
As most waited features

**Comment by fepan** [comment]
+1 on the name change.

**Comment by rkamudhan** [comment]
@fepan Will cut all the red tape soon on it... :)

**Comment by Billy99** [comment]
Question: We are bouncing around the idea of moving to a Device Plugin or an Admission Controller. Do we want CNI in the name?

**Comment by rkamudhan** [comment]
I will be CNI only..

**Comment by rkamudhan** [comment]
The **_userspace-cni network plugin_** got approved by Intel internal. Will change the name in the README.md.

**Comment by rkamudhan** [comment]
we will be missing some commits from @kangasta, we like to discuss on it..
