### ISSUE TITLE
Can't build - one package in vendored govpp is missing

### ISSUE THREAD

**Issue by vadorovsky** [intel/userspace-cni-network-plugin#25]
I see the following error when I'm trying to build:

```
../cnivpp/api/interface/interface.go:28:2: cannot find package "git.fd.io/govpp.git/core/bin_api/interfaces" in any of:
        /home/mrostecki/go/src/github.com/intel/userspace-cni-network-plugin/vendor/git.fd.io/govpp.git/core/bin_api/interfaces (vendor tree)
        /usr/lib64/go/1.12/src/git.fd.io/govpp.git/core/bin_api/interfaces (from $GOROOT)
        /home/mrostecki/go/src/git.fd.io/govpp.git/core/bin_api/interfaces (from $GOPATH)
../cnivpp/api/bridge/bridge.go:26:2: cannot find package "git.fd.io/govpp.git/core/bin_api/l2" in any of:
        /home/mrostecki/go/src/github.com/intel/userspace-cni-network-plugin/vendor/git.fd.io/govpp.git/core/bin_api/l2 (vendor tree)
        /usr/lib64/go/1.12/src/git.fd.io/govpp.git/core/bin_api/l2 (from $GOROOT)
        /home/mrostecki/go/src/git.fd.io/govpp.git/core/bin_api/l2 (from $GOPATH)
../cnivpp/api/vhostuser/vhostuser.go:26:2: cannot find package "git.fd.io/govpp.git/core/bin_api/vhost_user" in any of:
        /home/mrostecki/go/src/github.com/intel/userspace-cni-network-plugin/vendor/git.fd.io/govpp.git/core/bin_api/vhost_user (vendor tree)
        /usr/lib64/go/1.12/src/git.fd.io/govpp.git/core/bin_api/vhost_user (from $GOROOT)
        /home/mrostecki/go/src/git.fd.io/govpp.git/core/bin_api/vhost_user (from $GOPATH)
make: *** [Makefile:74: build] Error 1
```

And indeed, the `core/bin_api/l2` package is missing inside `vendor/` directory.

**Comment by Billy99** [comment]
First, sorry for letting this sit for so long. I will do better about monitoring the GitHub issues and addressing in a timely manner.

When I first start this endeavor, I was new to GO and just tried to get this working. So the current solution is to install the required VPP API files using the following.

Install any additional packages needed to run 'make install' (CentOS: wget cpio rpm  Ubuntu: binutils wget):
```
$ sudo make install-dep
```
Install VPP required files (without actually installing VPP):
```
$ sudo make install
```
To remove the VPP files install with 'make install', use:
```
$ sudo make clean
```

I am now looking back at the Makefile and I should fix this to add the files to vendor and handle different versions of VPP cleanly. I will leave this open to track that change, but hopefully the 'make install' will help short term.
