### ISSUE TITLE
cni doesn't create socket when using vhostuserclient

### ISSUE THREAD

**Issue by M258** [intel/userspace-cni-network-plugin#44]
I create ovs-dpdk NetworkAttachmentDefinition as follows. after pod create, I can see vhostuserclient ports in ovs, but socket in vhost-server-path doesn't exist. Should socket be created by userspace cni or by other？

> apiVersion: "k8s.cni.cncf.io/v1"
> kind: NetworkAttachmentDefinition
> metadata:
>   name: userspace-ovs-net-2
> spec:
>   config: '{
>         "cniVersion": "0.3.1",
>         "type": "userspace",
>         "name": "userspace-ovs-net-2",
>         "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig",
>         "logFile": "/var/log/userspace-ovs-net-2-cni.log",
>         "logLevel": "debug",
>         "host": {
>                 "engine": "ovs-dpdk",
>                 "iftype": "vhostuser",
>                 "netType": "bridge",
>                 "vhost": {
>                         "mode": "client"
>                 },
>                 "bridge": {
>                         "bridgeName": "br0"
>                 }
>         },
>         "container": {
>                 "engine": "ovs-dpdk",
>                 "iftype": "vhostuser",
>                 "netType": "interface",
>                 "vhost": {
>                         "mode": "server"
>                 }
>         },
>         "ipam": {... ...}
>   }'

**Comment by garyloug** [comment]
Hi @M258 
If OVS-DPDK is listing vhost ports, then OVS should have created a socket file (assuming there were no errors in OVS logs). These sockets are usually placed in a default location like /var/run/openvswitch/ (I think this can change with different versions of OVS).

If all pods were to mount this directory, then all pods would see all sockets. You can do this but it’s not ideal. Userspace CNI can create a “private” directory for your pod and move the appropriate socket(s) in here. Then your pod must mount this directory.
This “private” directory should be referenced in the pod spec as shared-dir. Something like this:
```
   - mountPath: /vhu
      name: shared-dir
  volumes:
  - name: shared-dir
    hostPath:
      path: /var/run/openvswitch/pod1/
```
This will create the “pod1” directory on the host, place the sockets in here and then K8s will mount it as /vhu within the pod. The “private” directory can be anywhere on the host but note that there does seem to be some [problems](https://github.com/intel/userspace-cni-network-plugin/issues/42) when moving sockets over volumes.

I’m less familiar with vhostuserclient, but the vhost-server-path seems to get set to shared-dir in the pod spec as mentioned above. If you’re not setting shared-dir then I’d check the default OVS location.

**Comment by johnoloughlin** [comment]
Hello @M258 

Your dpdk app will need to create the socket in the correct directory.
ovs has deprecated vhostuser so we must use vhostuserclient


Below are the manual steps you would use to set up ovs and the dpdk app.
userspacecni will automatically do the ovs steps for you, but you need to set the container mount points correctly
and the socket names need to match  

Create a directory for your dpdkvhostuserclient socket  
`mkdir -p /run/openvswitch/host/`  
Add a bridge in netdev mode  
`ovs-vsctl add-br br-5 -- set bridge br-5 datapath_type=netdev`  
Add dpdkvhostuserclient interface to the bridge, note socket will not be created yet  
`ovs-vsctl add-port br-5 vhost-user-1 -- set Interface vhost-user-1 type=dpdkvhostuserclient options:vhost-server-path=/run/openvswitch/host/host-net1`  

Start testpmd in interactive mode  
`./build/app/dpdk-testpmd -l 6,8 --vdev "net_virtio_user0,path=/run/openvswitch/host/host-net1,server=1,queue_size=2048" --in-memory --single-file-segments --no-pci -- -i`  
At this point the interface should be up and connected. This can be verified in the dpdk-testpmd terminal with:  
`show port info all`  
To start traffic in the dpdk-testpmd terminal type:  
`set fwd txonly` followed by `start`  
To check if packets are been transmitted in testpmd run:  
`show port stats 0`  
To check if packets are been revived in ovs, in a new terminal run:  
`ovs-ofctl dump-ports br-5`
