### ISSUE TITLE
Code quality improvements

### ISSUE THREAD

**Issue by przemeklal** [intel/userspace-cni-network-plugin#55]
I opened a number of PRs with code changes from @p00rman who couple of weeks ago added unit tests, fixed issues discovered by his unit tests and improved Makefiles and documentation. All of this should significantly improve quality of the userspace-cni plugin. I noticed that issues with newer Golang versions seem to be resolved as well.

Recommended order of merging is pretty straightforward - patches should be merged one by one, from #46 to #54.

I created a branch on my fork that shows the final result of merging those patches, so you can have a look at the final effect: https://github.com/przemeklal/userspace-cni-network-plugin/tree/unit_tests_and_fixes_integration

You can prepare it by yourself by executing below script:
```
#!/bin/bash

# prepare working directory
mkdir -p $GOPATH/src/github.com/intel
cd $GOPATH/src/github.com/intel
git clone https://github.com/przemeklal/userspace-cni-network-plugin.git userspace-cni-network-plugin
cd userspace-cni-network-plugin

# checkout and merge all patches
git checkout userspace_unit_tests
git merge origin/docker_test_review -m "merge origin/origin/docker_test_review"
git merge origin/fix_configdata_SaveRemoteConfig -m "merge origin/fix_configdata_SaveRemoteConfig"
git merge origin/fix_null_pointer_and_error_handling -m "merge origin/fix_null_pointer_and_error_handling"
git merge origin/fix_null_pointer_k8sclient -m "origin/fix_null_pointer_k8sclient"
git merge origin/fix_path_handling -m "origin/fix_path_handling"
git merge origin/fix_typos -m "origin/fix_typos"
git merge origin/fix_vpp_test -m "origin/fix_vpp_test"
git merge origin/unittests_doc -m "origin/unittests_doc"

# execute all tests and build targets
make clean
make install-dep
make install
make
make test-all
make coverage-all
```

@Billy99 @garyloug Could you please take a look? I'll be happy to answer any questions or work on any additional fixes. There's also one extra patch pending that switches from glide to go modules and I'm going to push that one as well.

**Comment by przemeklal** [comment]
Code coverage:
```
Coverage: 94.1% of statements
github.com/intel/userspace-cni-network-plugin/cniovs/cniovs.go - 95.4%
github.com/intel/userspace-cni-network-plugin/cniovs/localdb.go - 86.4%
github.com/intel/userspace-cni-network-plugin/cniovs/ovsctrl.go - 100.0%
github.com/intel/userspace-cni-network-plugin/cniovs/ovsctrl_fake.go - 100.0%
github.com/intel/userspace-cni-network-plugin/logging/logging.go - 100.0%
github.com/intel/userspace-cni-network-plugin/pkg/annotations/annotations.go - 97.7%
github.com/intel/userspace-cni-network-plugin/pkg/configdata/configdata.go - 98.8%
github.com/intel/userspace-cni-network-plugin/pkg/k8sclient/k8sclient.go - 89.8%
github.com/intel/userspace-cni-network-plugin/userspace/userspace.go - 84.9%
```

**Comment by garyloug** [comment]
Merged.
Thanks @p00rman @przemeklal and @killianmuldoon for tests and code improvements. Thanks @Billy99 for review.
